version: "3.7"
services:
  db:
    image: "postgres:12.1"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
volumes:
  my_dbdata:
