spring:
  application:
    name: spring-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:54320/
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: spring_db
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: logs
    basedir: ./tomcat
